# -*- coding: utf-8 -*-
"""Winequality-red Regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oebQ_q2b12KO5Dz4Zi2nZvOEtGlwwHG4
"""

import pandas as pd
import numpy as np

dataset = pd.read_csv('/content/winequality-red.csv')

dataset.describe()

dataset.info()

x = dataset.iloc[: , :-1].values
y = dataset.iloc[: , -1].values

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x , y,test_size = 0.25)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

t_train = y_train.reshape(len(y_train),1)
t_test = y_test.reshape(len(y_test),1)



x_sc = StandardScaler()
y_sc = StandardScaler()

x_std_train = x_sc.fit_transform(x_train)
y_std_train = x_sc.fit_transform(t_train)

x_std_test = x_sc.transform(x_test)
y_std_test = x_sc.transform(t_test)

from sklearn.ensemble import RandomForestRegressor

r_reg = RandomForestRegressor(n_estimators = 250)

from sklearn.preprocessing import PolynomialFeatures

x_poly = PolynomialFeatures(degree = 5)
x_poly =x_poly.fit_transform(x_train)

r_reg.fit(x_train,y_train)

temp =  PolynomialFeatures(degree = 5)
temp = temp.fit_transform(x_test)

r_pred = r_reg.predict(x_test)

from sklearn.metrics import r2_score

r = r2_score(y_test,r_pred)

print(r)

